### ISSUE TITLE
[Feature Request] Some features you can implement from Kotatogram

### ISSUE THREAD

**Issue by Neurotoxin001** [TDesktop-x64/tdesktop#63] opened 2022-03-11 09:16 UTC
Unofficial Telegram Desktop fork named [Kotatogram](https://github.com/kotatogram/kotatogram-desktop/) suspended development but it's have many QoL features that you can implement in 64Gram.

**1**. Remember forward mode when you select it in forward menu:

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157836028-04599e0f-74e1-4c92-b3b9-9b766e1d557e.png)
</details>

**2**. Hide "Edit" folder:
<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157836193-41b5c978-ca65-4776-8edf-5b31ed8d570e.png)
</details>

**3**. Group media in album when forwarding without quotes and captions:
<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157836802-9445ae31-cb49-4e20-86b4-2193929f3113.png)
</details>

**4**. "Go to chat" button in forward menu:
<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157837105-25c48819-1b24-479d-ad30-bea103177eff.png)
</details>

**5**. Compact chat list:

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157837334-49a13fc5-6e12-4d30-84bc-836fea3fd821.png)
</details>

**6**. Disable chat themes.

**7**. Stickers size:

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157839532-37f7f6b7-2553-41d6-85e1-09aef3fa61a7.png)
</details>

**8**. Show special icon if post written by channel, example post https://t.me/kotatogram_ru/243?comment=150837:

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157840462-1cc01c30-02c1-452f-8f68-8636a38bd153.png)
</details>

**9**. Copy link / username  of channel/user/group by click.

**10**. Add "clear history" and "delete chat" buttons in profile:

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157890590-8ef66cd9-7eeb-4c46-8667-4ac252c561b4.png)
</details>

**11**. When you share post with "share arrow" or by pressing "F" button above make saving post to saved messages instantly, without confirming. Now I must confirm it:

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157907003-185b1bb0-44e7-435b-a88d-6670758e0d6c.png)
</details>

**12**. Add "discuss" button to channel info and "linked channel" to groups if channels are linked to them:

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157910232-87048b58-4053-4880-8d04-4ba72c145963.png)
</details>

**13**. Make video playback bar available for GIFs when they opened in full screen.

All these features you can get from Kotatogram sources without coding it by yourself.

**And feature that you have to do by yourself:**
Disable showing reactions on posts.

**And also I found some bugs:**

**1**. When "Always show scheduled button" enabled scheduled posts button is showing with red dot like there is scheduled posts, but it's not. You can get source of this feature without this bug from Kotatogram:

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157836548-d0d4b1b0-cb4b-4424-bfae-d1aee41ac725.png)
</details>

~~**2**. When you ban user from "Recent actions" in your group buttons is go out of borders if user name is too long:~~ UPD: Fixed (can't find right commit with this fix)

~~**3**. 64Gram replaces Telgram Desktop in default apps in Windows settings. Fix – https://github.com/kotatogram/kotatogram-desktop/commit/490b29b31c2bc03244820d610a3494b4a4ec0bea~~ UPD: Fixed

~~**4**. 64Gram is showing users that online in chats even if I disable showing my online. It's annoying for private chats with my 3-5 friends.~~ UPD: As it turned out, this is not a bug.

**5**. There is Forward button in scheduled messages when you select post. You can't press it:

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/39812401/157866162-d18bbcd3-196e-4edd-ab0f-58134f7553e3.png)
</details>

~~**6**. Single pinned message can't be unpinned in 1 click, it's always opens list of pinned messages like there is more than 1. Example channel - https://t.me/bbbreaking~~ UPD: As it turned out, this is not a bug.

~~**7**. After I forward message with buttons above (F button) - selection on post is not canceled.~~ UPD: Fixed https://github.com/TDesktop-x64/tdesktop/commit/a9b469b3d1ea152f54815487653e7441ad021502

~~**8**. There is no "Forward to saved" in right click menu if I click on caption, I must click on media. This is bad if post have album. I only can forward 1 media from post with album to saved messages from right click menu. To forward all media I must select all post manually and press "s" button above. Or "F" button. It's takes too much time. Example - https://t.me/ostorozhno_novosti/6454~~ UPD: Fixed

64Gram 1.0.22 beta

**Comment by Neurotoxin001** [comment] 2022-03-11 14:56
If you want, I can create tickets for each request and bug separately

**Comment by c0re100** [comment] 2022-03-11 20:45
Some "bugs" are a part of 64Gram feature, so it's not a bug, it's a feature :)
e.g.:
`64Gram is showing users that online in chats`
`Single pinned message can't be unpinned in 1 click`

**Comment by Neurotoxin001** [comment] 2022-03-11 21:27
> Some "bugs" are a part of 64Gram feature, so it's not a bug, it's a feature :)

Ok then can I ask why you release these features?
> 64Gram is showing users that online in chats

In small chats I still can't see who is online, I only see number of users. 

> Single pinned message can't be unpinned in 1 click

With this feature, I also can't figure out why it's needed.

**Comment by c0re100** [comment] 2022-03-11 22:03
> In small chats I still can't see who is online, I only see number of users.

Regular group(non supergroup) can't use getOnlines API (https://core.telegram.org/method/messages.getOnlines)

> With this feature, I also can't figure out why it's needed.

Cause it's easy to unpin in 1 click and so I need it

**Comment by Neurotoxin001** [comment] 2022-03-11 22:09
> Regular group(non supergroup) can't use getOnlines API

I mean supergroup with small amount of people. Maybe you can checkbox to enable/disable it please?

**Comment by fosam** [comment] 2022-03-12 00:47
> Some "bugs" are a part of 64Gram feature, so it's not a bug, it's a feature :) e.g.: `64Gram is showing users that online in chats` `Single pinned message can't be unpinned in 1 click`

Hi Boss!

I agree with you. 

There is one function that is so missed which is tagging the user by the `name` not the `username`

<details>
<summary>Screenshot</summary>
<img src=https://user-images.githubusercontent.com/52612348/157995699-c21defe2-39af-46c9-a958-a9c35e2a3db4.png>
</details>

In the screenshot, first one is the `username`, and second one is the `name` (blue color). In 64Gram it's <ins>only</ins> possible to tag by <ins>`username`</ins>

Can you please also add the possibility to tag by `name`? cause it's also convenient. For example, by clicking the right mouse button the user will be tagged as in the screenshot.

**Comment by Neurotoxin001** [comment] 2022-03-12 08:27
> Can you please also add the possibility to tag by name?

Please create your own ticket.

**Comment by T1MOXA** [comment] 2022-07-22 22:24
+ for compact chat list feature.
It will be nice to see it.

**Comment by Neurotoxin001** [comment] 2022-11-16 07:00
I'm back to 64Gram so these features is still not released:
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13

And these bugs too not fixed:
1, 5

1.0.53

**Comment by Neurotoxin001** [comment] 2022-11-16 21:43
Btw after you remove "Forward Without Quote" you also broke default Telegram Desktop "Forward Without Quote". Try to forward any post without quote to your saved messages from 64Gram:
1. Select any message (with picture and caption) and press "Classic" forward
2. Choose any user or group and click on that message before sending it
3. Uncheck "Show sender name" and "Show caption" checkboxes
4. Press Change recipient and choose saved messages
5. Message will be forwarded like simple repost, with quote
6. Now do the same on Telegram Desktop
7. Message will be forwarded without quote

**Comment by fosam** [comment] 2022-11-17 00:20
> Btw after you remove "Forward Without Quote" you also broke default Telegram Desktop "Forward Without Quote". Try to forward any post without quote to your saved messages from 64Gram:
> 
> 1. Select any message (with picture and caption) and press "Classic" forward
> 2. Choose any user or group and click on that message before sending it
> 3. Uncheck "Show sender name" and "Show caption" checkboxes
> 4. Press Change recipient and choose saved messages
> 5. Message will be forwarded like simple repost, with quote
> 6. Now do the same on Telegram Desktop
> 7. Message will be forwarded without quote

Duplicate of #119

**Closed** 2023-07-26 00:18 UTC
Labels: bug, enhancement
