### ISSUE TITLE
[Bug Report] New shortcuts are not working properly and crashing :c

### ISSUE THREAD

**Issue by old-izayoi** [TDesktop-x64/tdesktop#15] opened 2020-10-25 19:38 UTC
### Expected behaviour
Opens forward menu on Alt+F and copies text or link on Alt+C

### Actual behaviour
Opens the forward menu (Share menu) on both of the shortcuts when msg is selected. And crashes the client whenever these shortcuts are used while there is a selected text from some msg

**Comment by c0re100** [comment] 2020-10-25 20:34
Actually, I can't reproduce :( 
Do you have crash log? check out telegram `log.txt`.

**Comment by old-izayoi** [comment] 2020-10-25 20:42
@c0re100
I tried to launch it w/o fontmod, but it crashed again.

[2020.10.25 23:39:41] App Info: reading accounts info...
[2020.10.25 23:39:41] App Info: reading encrypted info...
[2020.10.25 23:39:41] App Info: reading map...
[2020.10.25 23:39:41] App Info: reading encrypted map...
[2020.10.25 23:39:41] App Info: reading encrypted user settings...
[2020.10.25 23:39:41] App Info: encrypted user settings read.
[2020.10.25 23:39:41] App Info: reading encrypted mtp data...
[2020.10.25 23:39:41] MTP Info: read keys, current: 5, to destroy: 0
[2020.10.25 23:39:41] Map read time: 5
[2020.10.25 23:39:41] App Info: reading encrypted mtp config...
[2020.10.25 23:39:41] Export Info: Destroy top bar by controller removal.
[2020.10.25 23:39:42] Network error: 203
[2020.10.25 23:39:42] Fallback to default language: English...
```
[2020.10.25 23:39:42] Message Info: bad message notification received (error_code 33) for msg_id = 6887660307298306808, seq_no = 40
[2020.10.25 23:39:42] Message Info: bad message notification received, msgId 6887660307298306808, error_code 33
```
[2020.10.25 23:39:43] API Warning: not loaded minimal channel applied.
[2020.10.25 23:39:43] API Warning: not loaded minimal channel applied.
[2020.10.25 23:39:48] API Error: Got empty admins list from server.

**Comment by old-izayoi** [comment] 2020-10-25 20:50
Also **RPC Error** and **Admin request** appears when doing that in dms, previously was trying out that only in x64 disc group

[2020.10.25 23:45:15] App Info: reading accounts info...
[2020.10.25 23:45:15] App Info: reading encrypted info...
[2020.10.25 23:45:15] App Info: reading map...
[2020.10.25 23:45:15] App Info: reading encrypted map...
[2020.10.25 23:45:15] App Info: reading encrypted user settings...
[2020.10.25 23:45:15] App Info: encrypted user settings read.
[2020.10.25 23:45:15] App Info: reading encrypted mtp data...
[2020.10.25 23:45:15] MTP Info: read keys, current: 5, to destroy: 0
[2020.10.25 23:45:15] Map read time: 5
[2020.10.25 23:45:15] App Info: reading encrypted mtp config...
[2020.10.25 23:45:15] Export Info: Destroy top bar by controller removal.
[2020.10.25 23:45:16] Network error: 203
[2020.10.25 23:45:16] Fallback to default language: English...
[2020.10.25 23:45:17] API Warning: not loaded minimal channel applied.
[2020.10.25 23:45:17] API Warning: not loaded minimal channel applied.
[2020.10.25 23:46:53] Message Info: bad message notification received (error_code 33) for msg_id = 6887662157143555112, seq_no = 192
**[2020.10.25 23:47:11] RPC Error: request 100 got fail with code 400, error CHAT_ADMIN_REQUIRED**
[2020.10.25 23:47:12] Message Info: bad message notification received (error_code 33) for msg_id = 6887662238817356196, seq_no = 214
[2020.10.25 23:47:12] Message Info: bad message notification received, msgId 6887662238817356196, error_code 33

**Comment by c0re100** [comment] 2020-10-25 20:53
sadly, `bad message notification received`or `CHAT_ADMIN_REQUIRED` error message come from server side.
So it's not related to forward shortcut crash...

ref: https://github.com/telegramdesktop/tdesktop/blob/bc7925985c06b6eafec9000edc0e02b553c00cad/Telegram/SourceFiles/mtproto/session_private.cpp#L1502
https://github.com/telegramdesktop/tdesktop/blob/371510cfe23b0bd226de8c076bc49248fbe40c26/Telegram/SourceFiles/mtproto/mtp_instance.cpp#L1098

**Comment by old-izayoi** [comment] 2020-10-25 21:22
Is there any way to track the error? i think it's possible since it shows loading animation on the cursos just a second before force closing the client and yeah, how do i enable the debug mode?  i just saw this debug mode: [FALSE]

**Comment by c0re100** [comment] 2020-10-25 21:57
> Is there any way to track the error? i think it's possible since it shows loading animation on the cursos just a second before force closing the client and yeah, how do i enable the **debug mode**? i just saw this **debug mode: [FALSE]** at the beginning of the log

I don't know...
debug mode can be open via settings panel.
and type debugmode
But I'm not sure this mode can collect useful information...
Cause debugmode is logging network request only..

**Comment by JasonKhew96** [comment] 2020-10-31 15:24
Reproduced: 
**segmentation fault** on **selected text** when shorcut key pressed
works well when **message** is selected but not with **text** selected

**Comment by c0re100** [comment] 2020-10-31 19:27
Will be fixed in the next version.

**Closed** 2020-11-05 14:22 UTC
Labels: bug
